divisor = int(input("Entra el teu divisor: "))
dividend = int(input("Entra el teu dividend"))
Quocient = (dividend)//(divisor)
Residu = (dividend)%(divisor)
print(f"Divisió: {dividend}/{divisor}")
print(f"Quocient: {Quocient}")
print(f"Residu: {Residu}")